sensor_kit_base_link:
  # camera0/camera_link:
  #   x: 0.0
  #   y: 0.0
  #   z: 0.0
  #   roll: 0.0
  #   pitch: 0.0
  #   yaw: 0.0
  os_sensor_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  # velodyne_top_base_link:
  #   x: 0.0
  #   y: 0.0
  #   z: 0.0
  #   roll: 0.0
  #   pitch: 0.0
  #   yaw: 0.0
  # gnss_link:
  #   x: -0.1
  #   y: 0.0
  #   z: -0.2
  #   roll: 0.0
  #   pitch: 0.0
  #   yaw: 0.0
  # tamagawa/imu_link:
  #   x: 0.0
  #   y: 0.0
  #   z: 0.0
  #   roll: 3.14159265359
  #   pitch: 0.0
  #   yaw: 3.14159265359
